apiVersion: v1
kind: Pod
metadata:
  name: gpu-topo-aware
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
         limits:
             cpu: 0.1
             memory: 100Mi
             nvidia.com/gpu: 4
